apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tensorflow-notebook.fullname" . }}
  labels:
    app: {{ template "tensorflow-notebook.name" . }}
    chart: {{ template "tensorflow-notebook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "tensorflow-notebook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tensorflow-notebook.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: jupyter
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          imagePullPolicy: {{ .Values.jupyter.image.pullPolicy }}
          ports:
            - containerPort: 8888
              name: jupyter
          command:
            - jupyter
          args:
            - notebook
            - --allow-root
            - --ip=127.0.0.1 
            - --no-browser
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "tensorflow-notebook.fullname" . }}
                  key: password
          volumeMounts:
            - mountPath: /output/training_logs
              name: training-logs-volume
        - name: tensorboard
          image: "{{ .Values.tensorboard.image.repository }}:{{ .Values.tensorboard.image.tag }}"
          imagePullPolicy: {{ .Values.tensorboard.image.pullPolicy }}
          ports:
            - containerPort: 6006
              name: tensorboard
          command:
            - ./root/.local/bin/tensorboard
          args:
            - --logdir
            - --db sqlite:~/.tensorboard.db
            - --host
            - 127.0.0.1
          livenessProbe:
            httpGet:
              path: /
              port: 6006
          readinessProbe:
            httpGet:
              path: /
              port: 6006
          volumeMounts:
            - mountPath: /output/training_logs
              name: training-logs-volume
      volumes:
        - name: training-logs-volume
          emptyDir: {}
