apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "template.fullname" . }}
spec:
  rules:
  - host: ingress-{{ include "template.fullname" . }}.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "template.fullname" . }}
          servicePort: 5901
          
